version: '3.8'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency_app
    restart: always
    ports:
      - "8080:8080" # Приложение будет доступно на http://localhost:8080
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=currency_exchange;Username=yuqqirri;Password=1235
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: currency_db
    restart: always
    environment:
      POSTGRES_USER: yuqqirri
      POSTGRES_PASSWORD: 1235
      POSTGRES_DB: currency_exchange
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_manage
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pg_data: