version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency_app
    restart: always
    ports:
      - "8080:8080" # Swagger будет доступен на http://localhost:8080/swagger
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=currency_exchange;Username=yuqqirri;Password=1235
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: currency_db
    restart: always
    environment:
      POSTGRES_USER: yuqqirri
      POSTGRES_PASSWORD: 1235
      POSTGRES_DB: currency_exchange
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_manage
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # ƒоступ к базе через браузер: http://localhost:5050
    depends_on:
      - db

volumes:
  pg_data: