version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: currency_db
    restart: always
    environment:
      POSTGRES_USER: yuqqirri
      POSTGRES_PASSWORD: 1235
      POSTGRES_DB: currency_exchange
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_manage
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  pg_data: